api/urls.py
# urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('messages/', views.message_list, name='message-list'),
    path('messages/<int:pk>/', views.message_detail, name='message-detail'),
    path('product/imges/', views.product_images, name='product_imges'),
        path('product/imges/<int:id>/', views.product_image_id, name='product_imge_id'),

     path('product/imges/<int:pk>/', views.product_imge, name='product_imge'),

    path('product/imges/swapper', views.swapper_images, name='swapper_imges'),
    path('attendance/', views.AttendanceAPIView.as_view(), name='attendance-api'),



     

]

clints/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
  
    path('view/<int:id>/', views.fatch_clints, name='fatch_clints'),
    path('<int:id>/' , views.clint_bills_chart_admin , name="clint_bills_chart_admin"),
    path('chart/' , views.bills_chart_admin , name="bills_chart_admin"),

    path('chat/', views.clint_chat, name='clint_chat'),
    path('chat/<int:id>/', views.bills_and_payments_view, name='bills_and_payments_view'),
    path('payment/edit/<int:pk>/', views.edit_clintPymant, name='edit_clintPymant'),

     path('add/payment/<int:clint_id>/', views.add_payment_and_list, name='add-payment'),
    path('delete/payment/<int:payment_id>/', views.delete_payment, name='delete-payment'),



    path('repor/<int:client_id>/', views.client_report, name='client_report'),


]


    

lavantes/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from  main.views import *




from django.contrib.sitemaps.views import sitemap

from biles.sitemap import *

sitemaps = {
   'products': MainProductSitemap,
}




urlpatterns = [
   path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    path("admin/", admin.site.urls),
       path("main/", include('main.urls')), 
       path("account/" , include('users.urls')),
       path("biles/" , include('biles.urls')),
       path("customers/" , include('customers.urls')),
       path('employe/', include('employe.urls')),
       path('api/', include('api.urls')),
       path('payment/', include('money.urls')),

        path('', include('home.urls')),
        path('clints/', include('clints.urls')),
           path('chat/', include('chat.urls')),




]


 
 

# Serve static files during development
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from  . import views


urlpatterns = [

         path('test/',views.test, name='test'),


        path('buying-types/', views.buying_type_list, name='buying_type_list'),
        path('buying-types/new/', views.buying_type_create, name='buying_type_create'),
        path('buying-types/<int:pk>/edit/', views.buying_type_update, name='buying_type_update'),
        path('buying-types/<int:pk>/delete/', views.buying_type_delete, name='buying_type_delete'),




        path('buying/', views.general_buying_list, name='general_buying_list'), 
        path('buying/new/', views.create_general_buying, name='create_general_buying'),
        path('general_buying/edit/<int:pk>/', views.edit_general_buying, name='edit_general_buying'),
        path('general_buying/delete/<int:pk>/', views.delete_general_buying, name='delete_general_buying'),
        path('general_buying/view/<int:id>/', views.view, name="view_buying"),
        
    path('buying/jar/<int:pk>/', views.buying_jar, name='buying_jar'),
    path('buying/jar/<int:pk>/<int:id>/delete/', views.delete_jar_innner,name="delete_jar_innner"),

path('buying/<str:name>/<int:pk>/edit/', views.swiching, name="swiching"),



    path('buying/jar_off/<int:pk>/', views.buying_jar_off, name='buying_jar_off'),

    path('buying/jar_off/<int:pk>/<int:id>/delete/', views.delete_jar_off_innner,name="delete_jar_off_innner"),

      path('buying/pakage/<int:pk>/', views.buying_pakage, name='buying_pakage'),
      path('buying/pakage/<int:pk>/<int:id>/delete/', views.delete_pakage_inner,name="delete_pakage_inner"),



    


 path('material/', views.material_list, name='material-list'),  # List all materials
    path('material/add/', views.material_create, name='material-create'),  # Add a new material
    path('material/edit/<int:pk>/', views.material_edit, name='material-edit'),  # Edit a specific material
    path('material/delete/<int:pk>/', views.material_delete, name='material-delete'), 

   



path('material/raw/', views.raw_materials_list, name='raw_materials_list'),  # List page
    path('material/raw/add/', views.add_raw_material, name='add_raw_material'),  # Add page

      path('material/raw/update/<int:pk>/', views.raw_material_update, name='raw_material_update'),
    path('material/raw/delete/<int:pk>/', views.raw_material_delete, name='raw_material_delete'),


  path('buying/material/raw/<int:pk>/', views.buying_Rawmaterials, name='buying_Rawmaterials'),
  path('buying/material/raw/', views.raw_materials_summary,name="raw_materials_summary"),
      path('buying/material/raw/<int:pk>/<int:id>/delete/', views.delete_Rawmaterials,name="delete_Rawmaterials"),





path('material/Factor/', views.Factor_materials_list, name='Factor_materials_list'),  # List page
    path('material/Factor/add/', views.add_Factor_material, name='add_Factor_material'),  # Add page

      path('material/Factor/update/<int:pk>/', views.Factor_material_update, name='Factor_material_update'),
    path('material/Factor/delete/<int:pk>/', views.Factor_material_delete, name='Factor_material_delete'),




 path('buying/material/Factor/<int:pk>/', views.buying_Factormaterials, name='buying_Factormaterials'),
  path('buying/material/Factor/', views.factory_materials_summary, name='factory_materials_summary'),
 
      path('buying/material/Factor/<int:pk>/<int:id>/delete/', views.delete_Facorymaterials,name="delete_Factormaterials"),
       path('assets/', views.assets_list_view, name='assets-list'),  # List all materials
       path('assets/add/', views.Asstes_create, name='assets-create'),  # Add
      path('assets/edit/<int:pk>/', views.Asstes_edit, name='assets-edit'),  # Edit a specific material
      path('assets/delete/<int:pk>/', views.Asstes_delete, name='assets-delete'),  # Edit a specific material

          path('assets/json/', views.assets_list_json, name='assets-list-json'),
            path('buying/assets/<int:pk>/', views.buying_assets_inner,name="buying_assets_inner"),
                  path('buying/assets/<int:pk>/<int:id>/delete/', views.delete_assets,name="delete_assets"),
                  path('buying/pay/<int:id>/', views.create_clint_payment,name="makePyment"),

                #  path('buying/pay/', views.create_clint_payment,name="create_clint_payment"),



            path('buying/spendes/<int:pk>/', views.buying_Spendes_inner,name="buying_Spendes_inner"),
     path('buying/spendes/<int:pk>/<int:id>/delete/', views.delete_spendes,name="delete_spendes"),
                  









      

  

 


]

clints/models.py
from django.db import models


from django.conf import settings
import uuid

from django.db.models import Sum
from money.models import GeneralPayment , MoneySource

from django.utils import timezone

from django.core.validators import MinValueValidator, MaxValueValidator

class clints(models.Model):
    name = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_clint')
    tex = models.BigIntegerField(blank=True, null=True) 
    email = models.EmailField(blank=True, null=True)
    number = models.CharField(max_length=255 ,  null=True)
    is_company = models.BooleanField(default=0)
    company = models.TextField(blank=True, null=True)
    total_paied = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(9999999999)], default=0)
    total_buy = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(9999999)], default=0)
    balance = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(9999999)], default=0)
    address = models.TextField(blank=True, null=True)
    token = models.CharField(max_length=36, unique=True, default=uuid.uuid4)
    profile_image = models.ImageField(upload_to='clints/', blank=True, null=True)  # Image field for profile image


    def __str__(self):
        return self.name
    



    def get_total(self):
        # Import UdsBills from the bill app
        from main.models import GeneralBuying

        total_price = GeneralBuying.objects.filter(client=self).aggregate(total=Sum('price'))['total']
        self.total_buy= total_price
        self.save()
      
       
        
        return total_price if total_price else 0
    
    

    def get_total_payment(self):
        # Import UdsBills from the bill app
        from main.models import GeneralBuying

        total_price = ClintPayment.objects.filter(clint=self).aggregate(total=Sum('amount'))['total']
        self.total_paied= total_price
        self.save()
       
        
        return total_price if total_price else 0
    


    def save(self, *args, **kwargs): 
        # Save the instance first to ensure it's in the database
        is_new = self.pk is None  # Check if this is a new instance
        super().save(*args, **kwargs)

        if is_new:
            # Update calculated fields after the instance is saved
            self.total_buy = self.get_total()
            self.total_paied = self.get_total_payment()
            self.balance = self.total_buy - self.total_paied
            super().save(update_fields=['total_buy', 'total_paied', 'balance'])



    def calculate(self):
        self.balance = self.get_total() - self.get_total_payment()
        self.save()
        return self.balance


    
    def MakePyment(self , amount):
        pass



    def RemovePyment(self , amount):
        pass
       
    

    






    



from django.utils.timezone import now


class ClintPayment(models.Model):
    source = models.ForeignKey(MoneySource, on_delete=models.CASCADE , default=None)
    clint = models.ForeignKey(clints, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(default=now)
    note = models.TextField(default="None")
    payment_token = models.UUIDField(editable=False, unique=True, default=uuid.uuid4)  # Use default for automatic generation
    image = models.ImageField(upload_to='clints/pymnets/', blank=True, null=True)

    def __str__(self):
        return f"Payment of {self.amount} to {self.clint.name} on {self.date}"
    

    def save(self, *args, **kwargs):
        if not self.pk:  # Check if this is a new record
            super().save(*args, **kwargs)  # Save the EmployeePayment first

            # Create a general payment record
            note = f"Payment to clint  {self.clint.name}, amount: {self.amount}, note: {self.note}"
            
   
            general_payment = GeneralPayment.objects.create(
                amount=self.amount,
                date=self.date,
                note=note,
                source=self.source
            )
            
            self.payment_token = general_payment.payment_token  # Set the payment token
            self.clint.get_total_payment()
        



            

        super().save(*args, **kwargs)  # Save the EmployeePayment with the toke



    def delete(self, *args, **kwargs):
        try:
            general_payment = GeneralPayment.objects.get(payment_token=self.payment_token)
            general_payment.delete()  # Delete the corresponding GeneralPayment
            self.clint.get_total_payment()
        except GeneralPayment.DoesNotExist:
            pass  # No corresponding GeneralPayment found

        super().delete(*args, **kwargs)

    def remove(self):
        self.delete()

clints/forms.py
# forms.py
from django import forms
from .models import *

class CostomersForm(forms.ModelForm):
    class Meta:
        model = clints
        fields = [
            'name', 'email', 'number', 'address', 'profile_image', "company"
        ]
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter client name' , 'class': 'form-control custom-width' }),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter client email' , 'class': 'form-control custom-width' }),
            'number': forms.TextInput(attrs={'placeholder': 'Enter contact number' , 'class': 'form-control custom-width' }),
            'address': forms.TextInput(attrs={'placeholder': 'Enter client source' , 'class': 'form-control custom-width custom-hight' }),
            'profile_image': forms.ClearableFileInput(attrs={ 'class': 'form-control custom-width' }),
             'company': forms.TextInput(attrs={'placeholder': 'Enter company name' , 'class': 'form-control custom-width ' }),

              }










class ChangePasswordForm(forms.Form):
    token = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter new Password'}),
        label='New Token',
        required=True
    )
    confirm_token = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter new Password'}),
        label='Confirm Token',
        required=True
    )

    def clean(self):
        cleaned_data = super().clean()
        token = cleaned_data.get('token')
        confirm_token = cleaned_data.get('confirm_token')

        if token and confirm_token and token != confirm_token:
            raise forms.ValidationError('Tokens do not match')

        return cleaned_data




    









class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = clints
        fields = ['profile_image', 'name', 'tex', 'email', 'number', 'address',
            'is_company', 'company',]

        widgets = {
            'profile_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
             'name': forms.TextInput(attrs={'placeholder': 'Enter Costomer name' , 'class': 'custom-width font_size'  }),
             'tex': forms.NumberInput(attrs={'placeholder': 'Enter tax', 'class': 'custom-width font_size'}),   
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email', 'class': 'custom-width font_size'}),
            'number': forms.TextInput(attrs={'placeholder': 'Enter contact number','class': 'custom-width font_size'}),
            'address': forms.Textarea(attrs={'placeholder': 'Enter address' , 'class': 'custom-width  custom-hight'}),
            'is_company': forms.CheckboxInput(attrs={'placeholder': 'Is it a company?' , 'class': 'custom-width font_size '}),
            'company': forms.Textarea(attrs={'placeholder': 'Enter company name' , 'class': 'custom-width  custom-hight'}),



        }

class CostomersFormAdvanv(forms.ModelForm):
    class Meta:
        model = clints
        fields = [
            'name', 'tex', 'email', 'number', 'address',
            'is_company', 'company',  'profile_image'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter name'}),
            'tex': forms.NumberInput(attrs={'placeholder': 'Enter tax'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email'}),
            'number': forms.TextInput(attrs={'placeholder': 'Enter contact number'}),
            'address': forms.TextInput(attrs={'placeholder': 'Enter address'}),
            'is_company': forms.CheckboxInput(attrs={'placeholder': 'Is it a company?'}),
            'company': forms.TextInput(attrs={'placeholder': 'Enter company name'}),
      
            'token': forms.TextInput(attrs={'readonly': 'readonly', 'style': 'background-color: lightgray;'}),
            'profile_image': forms.ClearableFileInput(attrs={'class': 'form-control'}),

        }

    def __init__(self, *args, **kwargs):
        super(CostomersFormAdvanv, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(CostomersFormAdvanv, self).save(commit=False)
        # Generate token if it's not provided
        if not instance.token:
            instance.generate_token()  # Replace with your token generation logic
        if commit:
            instance.save()
        return instance
    



    




   

class ClintPymantForm(forms.ModelForm):
    class Meta:
        model = ClintPayment
        fields = ('source', 'amount', 'date', 'note', 'image')
        widgets = {
            'source': forms.Select(attrs={'class': 'form-control'}),
            'amount': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter amount'}),
            'date': forms.DateTimeInput(
                attrs={'class': 'form-control', 'placeholder': 'Enter date and time', 'type': 'datetime-local'}
            ),
            'note': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter Note'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

main/templates/clint/Add_clint.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="add-clint-container border">
    <a href="{% url 'upload_clients' %}" class="btn btn-primary right"
      >uplode csv</a
    >
    <h2 class="mt-5">Add Client</h2>

    <form method="post">
      {% csrf_token %}
      <div class="form-group row">
        <label
          for="{{ form.clint_name.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >Client Name:</label
        >
        <div class="col-md-9">{{ form.clint_name }}</div>
      </div>
      <div class="form-group row">
        <label
          for="{{ form.clint_tex.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >Client Text:</label
        >
        <div class="col-md-9">{{ form.clint_tex }}</div>
      </div>
      <div class="form-group row">
        <label
          for="{{ form.clint_email.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >Email:</label
        >
        <div class="col-md-9">{{ form.clint_email }}</div>
      </div>
      <div class="form-group row">
        <label
          for="{{ form.c_number.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >Contact Number:</label
        >
        <div class="col-md-9">{{ form.c_number }}</div>
      </div>
      <div class="form-group row">
        <label
          for="{{ form.c_sorce.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >Source:</label
        >
        <div class="col-md-9">{{ form.c_sorce }}</div>
      </div>
      <div class="form-group row">
        <label
          for="{{ form.clint_iban.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >IBAN:</label
        >
        <div class="col-md-9">{{ form.clint_iban }}</div>
      </div>
      <div class="form-group row">
        <label
          for="{{ form.is_company.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >Is Company:</label
        >
        <div class="col-md-9">{{ form.is_company }}</div>
      </div>
      <div class="form-group row">
        <label
          for="{{ form.clint_tr_name.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >TR Name:</label
        >
        <div class="col-md-9">{{ form.clint_tr_name }}</div>
      </div>
      <div class="form-group row">
        <label
          for="{{ form.image.id_for_label }}"
          class="col-md-3 col-form-label text-md-right"
          >Image URL:</label
        >
        <div class="col-md-9">{{ form.image }}</div>
      </div>
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">Add Client</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

main/templates/clint/clint_list.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="container mt-5">
  <h1 class="text-center mb-4">Client List</h1>
  <a href="{% url 'addclint' %}" class="btn btn-info btn-sm">add clint</a>

  <a href="{% url 'download_clints_csv' %}" class="btn btn-info btn-sm"
    >export</a
  >

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Contact Number</th>
        <th scope="col">Source</th>
        <th scope="col">Is Company</th>
        <th scope="col">full name</th>

        <th scope="col">Actions</th>
        <!-- Added Actions column for edit/view links -->
      </tr>
    </thead>
    <tbody>
      {% for clint in clints %}
      <tr>
        <th scope="row">{{ clint.id }}</th>
        <td>{{ clint.clint_name }}</td>
        <td>{{ clint.clint_email }}</td>
        <td>{{ clint.c_number }}</td>
        <td>{{ clint.c_sorce }}</td>
        <td>{{ clint.is_company|yesno:"Yes,No" }}</td>
        <!-- Better readability -->
        <td>{{ clint.clint_tr_name }}</td>

        <td>
          <a href="{% url 'fatch_clint' clint.id %}" class="btn btn-info btn-sm"
            >View</a
          >
          <a
            href="{% url 'update_clint' clint.id %}"
            class="btn btn-info btn-sm"
            >Edit</a
          >
          <!-- Add more actions if needed -->
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

main/templates/clint/fatch_clint.html
{% extends 'base.html' %} {% block content %}
<style>
  .card-header {
    display: flex;
    felx-diraction: row;
    justify-content: space-between;
  }

  /* Modal styles */
  .modal {
    display: none; /* Hidden by default */
    position: fixed;
    z-index: 1;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5); /* Black with opacity */
    overflow: auto;
  }
  .conform-bottons {
    padding: 10px;
    justify-content: center;
    align-item: center;
  }

  .modal-content {
    background-color: #fefefe;
    margin: 15% auto;
    padding: 20px;
    border: 1px solid #888;
    width: 50%;
    max-width: 400px;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }

  /* Close button */
  .close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }

  .close:hover,
  .close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
  }

  /* Button styles */
  .btn {
    padding: 10px 20px;
    margin-right: 10px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .btn-danger {
    background-color: #dc3545;
    color: white;
  }

  .btn-danger:hover {
    background-color: #c82333;
  }

  .btn-secondary {
    background-color: #6c757d;
    color: white;
  }

  .btn-secondary:hover {
    background-color: #5a6268;
  }
</style>

<div class="container mt-5">
  <h1 class="text-center mb-4">Client Details</h1>
  <div class="card">
    <div class="card-header">
      <h2>{{ clint.clint_name }}</h2>
      <form
        id="deleteForm"
        method="post"
        action="{% url 'fatch_clint' clint.id %}"
      >
        {% csrf_token %}
        <button
          type="button"
          class="btn btn-danger mt-3"
          onclick="showDeleteConfirmation()"
        >
          Delete Client
        </button>
        <a href="{% url 'clints' %}" class="btn btn-secondary mt-3"
          >Back to Client List</a
        >
      </form>

      <a href="{% url 'update_clint' clint.id %}" class="btn btn-primary mt-3"
        >Edit</a
      >
    </div>
    <div class="card-body">
      <p><strong>ID:</strong> {{ clint.id }}</p>
      <p><strong>Name:</strong> {{ clint.clint_name }}</p>
      <p><strong>English name:</strong> {{ clint.clint_tr_name }}</p>
      <p><strong>Email:</strong> {{ clint.clint_email }}</p>
      <p><strong>Contact Number:</strong> {{ clint.c_number }}</p>
      <p><strong>Source:</strong> {{ clint.c_sorce }}</p>
      <p><strong>Is Company:</strong> {{ clint.is_company|yesno:"Yes,No" }}</p>
      <p><strong>IBAN:</strong> {{ clint.clint_iban }}</p>
      <p>
        <strong>Image:</strong>
        {% if clint.image %}
        <img
          src="{{ clint.image }}"
          alt="Client Image"
          class="img-thumbnail"
          style="max-width: 200px"
        />
        {% else %} N/A {% endif %}
      </p>
    </div>
  </div>
  <div class="mt-4 text-center"></div>

  <div id="confirmModal" class="modal">
    <div class="modal-content">
      <span class="close" onclick="closeModal()">&times;</span>
      <p>Are you sure you want to delete client '{{ clint.clint_name }}'?</p>
      <input type="hidden" name="delete" />
      <div class="conform-bottons">
        <button type="submit" form="deleteForm" class="btn btn-danger">
          Confirm Delete
        </button>
        <button type="button" class="btn btn-secondary" onclick="closeModal()">
          Cancel
        </button>
      </div>
    </div>
  </div>
</div>

<script>
  // Show confirmation modal
  function showDeleteConfirmation() {
    var modal = document.getElementById("confirmModal");
    modal.style.display = "block";
  }

  // Close modal
  function closeModal() {
    var modal = document.getElementById("confirmModal");
    modal.style.display = "none";
  }
</script>
{% endblock %}

main/templates/clint/payment_form.html
{% extends 'usd_bar.html' %} {% block content %} {% load biles_filters %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Responsive Client Payment Form</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <style>
      .form-container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f8f9fa;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      }
      @media (max-width: 576px) {
        h2 {
          font-size: 1.5rem;
        }
      }
    </style>
  </head>
  <body>
    <div class="container mt-5">
      <div class="form-container">
        <h2 class="text-center">Client Payment Form</h2>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="id_source">Source</label>
            {{ form.source }} {% if form.source.errors %}
            <div class="text-danger">{{ form.source.errors }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_clint">Client</label>
            {{ form.clint }} {% if form.clint.errors %}
            <div class="text-danger">{{ form.clint.errors }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_amount">Amount</label>
            {{ form.amount }} {% if form.amount.errors %}
            <div class="text-danger">{{ form.amount.errors }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_date">Date</label>
            {{ form.date }} {% if form.date.errors %}
            <div class="text-danger">{{ form.date.errors }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_note">Note</label>
            {{ form.note }} {% if form.note.errors %}
            <div class="text-danger">{{ form.note.errors }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            <label for="id_image">Image</label>
            {{ form.image }} {% if form.image.errors %}
            <div class="text-danger">{{ form.image.errors }}</div>
            {% endif %}
          </div>
          <button type="submit" class="btn btn-primary btn-block">
            Submit
          </button>
        </form>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>
{% endblock %}

main/templates/clint/pymantform.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <label for="source">Source:</label>
    {{ form.source }}
    <div class="text-danger">{{ form.source.errors }}</div>
  </div>
  <div class="form-group">
    <label for="clint">Clint:</label>
    {{ form.clint }}
    <div class="text-danger">{{ form.clint.errors }}</div>
  </div>
  <div class="form-group">
    <label for="date">Date:</label>
    {{ form.date }}
    <div class="text-danger">{{ form.date.errors }}</div>
  </div>
  <div class="form-group">
    <label for="note">Note:</label>
    {{ form.note }}
    <div class="text-danger">{{ form.note.errors }}</div>
  </div>
  <div class="form-group">
    <label for="image">Image:</label>
    {{ form.image }}
    <div class="text-danger">{{ form.image.errors }}</div>
  </div>
  <button type="submit" class="btn btn-primary">Submit Payment</button>
</form>

main/templates/clint/upload_clients.html
<!-- templates/upload_clients.html -->
{% extends 'base.html' %} {% block content %}
<div class="container mt-5">
  <h2>Upload Clients CSV</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="csv_file">CSV File</label>
      <input
        type="file"
        class="form-control"
        id="csv_file"
        name="csv_file"
        required
      />
    </div>
    <button type="submit" class="btn btn-primary mt-3">Upload</button>
  </form>
  {% if messages %}
  <div class="mt-3">
    {% for message in messages %}
    <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
  </div>
  {% endif %}
</div>
{% endblock %}